---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
      when: ansible_pkg_mgr == 'yum'
      apt:
        name: "apache2"
        state: "present"
      when: ansible_pkg_mgr == 'apt'
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
      when: ansible_pkg_mgr == 'yum'
      service:
        name: apache2
        state: started
        enabled: True
      when: ansible_pkg_mgr == 'apt'
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
