---
- hosts: webservers 
  become: True
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install httpd
      apt:
        name: apache2
        state: present
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
